CREATE TABLE IF NOT EXISTS users(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR NOT NULL,
    login VARCHAR NOT NULL,
    name VARCHAR,
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa(
    rating_id INTEGER PRIMARY KEY,
    rating VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS films(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL CHECK (release_date > '1895-12-28'),
    duration INTEGER NOT NULL,
    rate INTEGER NOT NULL,
    rating_id INTEGER REFERENCES mpa(rating_id)
);

CREATE TABLE IF NOT EXISTS genre(
    genre_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS film_genre(
    film_id INTEGER NOT NULL REFERENCES films(id),
    genre_id INTEGER NOT NULL REFERENCES genre(genre_id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friendship(
    user_id INTEGER NOT NULL REFERENCES users(id),
    friend_id INTEGER NOT NULL REFERENCES users(id),
    PRIMARY KEY(user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS liked_films(
    user_id INTEGER NOT NULL REFERENCES users(id),
    film_id INTEGER NOT NULL REFERENCES films(id),
    PRIMARY KEY (user_id, film_id)
);